### ISSUE TITLE
An instance of Gazebo is not running.

### ISSUE THREAD

**Issue by franjagra** [grvcTeam/grvc-ual#30]
I am trying to use UAL but when I run  `roslaunch px4_bringup spawn_robot.launch` I get the following message:

```
auto-starting new master
process[master]: started with pid [2552]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 93a5e0b0-4ef2-11e8-82c4-342387f4e2b1
process[rosout-1]: started with pid [2626]
started core service [/rosout]
process[spawn_gzmodel_1-2]: started with pid [2633]
process[run_px4sitl_1-3]: started with pid [2680]
process[run_mavros_1-4]: started with pid [2681]
An instance of Gazebo is not running.
[spawn_gzmodel_1-2] process has finished cleanly
log file: /home/vigus/.ros/log/93a5e0b0-4ef2-11e8-82c4-342387f4e2b1/spawn_gzmodel_1-2*.log
```

Does it happen to someone else?

**Comment by arturotorresg** [comment]
Hi! Can you send us the content of the following files? 
 * gzserver.out
 * gzserver.err
 * gzclient.out
 * gzclient.err 
They are located in /tmp/px4_sitl_files.

**Comment by franreal** [comment]
Hi! `spawn_robot.launch` from package `px4_bringup` does not run a Gazebo server, it expects a server to be running and spawns a robot in it. In the case you are not running any Gazebo server, the error you get is the expected behaviour.

Try `roslaunch px4_bringup test_simulate.launch` and let us know if it does not work.

**Comment by franjagra** [comment]
thanks for the answer, It works
