### ISSUE TITLE
Spawn gzmodel should wait Gazebo to be ready

### ISSUE THREAD

**Issue by arturotorresg** [grvcTeam/grvc-ual#41]
In computers where Gazebo takes more time to load, trying to spawn the robot while Gazebo is not loaded fails, blocking Gazebo. It can be fixed increasing the sleep time before trying to spawn, but this is arbitrary.

There should be a way to know when Gazebo is ready to spawn.

**Comment by franreal** [comment]
A possible solution is to `rospy.wait_for_service('/gazebo/spawn_sdf_model')` instead of blindly `time.sleep(x)` in https://github.com/grvcTeam/grvc-ual/blob/master/px4_bringup/scripts/spawn_gzmodel.py#L157

However, this (or other) solution should be tested in different computers to assure it's solid before closing the issue.
